name: scanalia
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  qr_code_utils: ^0.0.1
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  image_picker: ^1.0.4
  ficonsax: ^0.0.3
  auto_route: ^7.8.4
  flutter_svg: ^2.0.7
  dotted_border: ^2.1.0
  awesome_snackbar_content: ^0.1.3
  provider: ^6.0.5
  path_provider: ^2.1.1
  wiflutter: ^0.0.6
  qr_flutter: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  isar_generator: ^3.1.0+1
  auto_route_generator: ^7.3.2
  flutter_launcher_icons: ^0.13.1


flutter:
  uses-material-design: true

  assets:
    - assets/

flutter_launcher_icons:
  android: "launcher_icon"
  image_path: "assets/logo.png"
  min_sdk_android: 21