List<String> messages = [
  "Natalia, tu valentía es una inspiración para todos nosotros.",
  "La determinación de Natalia no conoce límites.",
  "Cada desafío que enfrenta Natalia es una oportunidad para crecer.",
  "Natalia, eres un ejemplo de superación y fuerza interior.",
  "La perseverancia de Natalia es un farco de esperanza en tiempos difíciles.",
  "Tus sueños son el motor de tu éxito, Natalia.",
  "Natalia, tus logros son un testimonio de tu dedicación.",
  "La sonrisa de Natalia ilumina el día de todos a su alrededor.",
  "Natalia, tu positividad es contagiosa y transformadora.",
  "Eres un rayo de luz en la vida de todos, Natalia.",
  "Natalia, el mundo es un lugar mejor gracias a ti.",
  "Nunca dudes de tu capacidad, Natalia. Estás destinada a lograr grandes cosas.",
  "La fortaleza de Natalia no tiene comparación. ¡Sigue brillando!",
  "Natalia, tu presencia hace que todo sea más especial.",
  "En tu camino, Natalia, solo hay éxito y felicidad.",
  "Cada día es una página en blanco, y Natalia es la autora de su propio destino.",
  "Siempre recuerda que tendras un hogar conmigo.",
  "Eres increible, jamas te rindas, el mundo es tuyo Natalia."
];
